### ISSUE TITLE
centos and cestos-stream have the same id

### ISSUE THREAD

**Issue by frenzymadness** [devexp-db/distgen#120]
In S2I Python container, we have some conditions based on `config.os.id` and I've discovered that Centos stream has the same id as Centos. I believe that those systems are very different and therefore they should have different ids in distgen.

Am I wrong?

Cc: @phracek

**Comment by phracek** [comment]
Similar to this one https://github.com/devexp-db/distgen/blob/main/distgen/distconf/lib/centos.yaml

**Comment by frenzymadness** [comment]
There already is a file for centos stream but it inherits the id from centos, see: https://github.com/devexp-db/distgen/blob/main/distgen/distconf/centos-stream-9-x86_64.yaml

**Comment by frenzymadness** [comment]
Fixed in https://github.com/devexp-db/distgen/commit/350e90fc803167435282c433cc57c721992dbb6a
