### ISSUE TITLE
Add `matrix: include` to multispec

### ISSUE THREAD

**Issue by frenzymadness** [devexp-db/distgen#128]
We use distgen in s2i Python container and the matrix: exclude part of our [multispec.yml](https://github.com/sclorg/s2i-python-container/blob/master/specs/multispec.yml) is growing so it might be better for us to specify the opposite – include instead of exclude, which would allow us to say what exact combinations we want.

I might try to implement this to distgen. What do you think about it?

**Comment by praiskup** [comment]
I'm +1, but we should probably ask @zmiklank?

**Comment by zmiklank** [comment]
If this change would be backward compatible - preserving the `matrix: exclude`, I am also +1.
