### ISSUE TITLE
PyPI readme is empty?

### ISSUE THREAD

**Issue by praiskup** [devexp-db/distgen#133]
See: https://pypi.org/project/distgen/

**Comment by zmiklank** [comment]
I think this can be fixed with adding long description to the `setup.py`, see [1] and linked PR.

[1] https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/

**Comment by zmiklank** [comment]
Should be fixed with https://github.com/devexp-db/distgen/pull/134. We will see after release though.

**Comment by zmiklank** [comment]
Readme is now available in PyPI in proper form https://pypi.org/project/distgen/.
