### ISSUE TITLE
CI for RPM packaging

### ISSUE THREAD

**Issue by praiskup** [devexp-db/distgen#31]
There's `distgen.spec` file, but:

- [ ] we can not easily submit copr build from travis NOW, this either ugly hacks, or waiting for new copr features
- [x] the spec file is python2 only (but fedora's default should be python3)
- [x] make check` fails, since there are not specified all test BuildRequries https://copr.fedorainfracloud.org/coprs/praiskup/distgen/build/598526/

**Comment by bkabrda** [comment]
I'll work on this, no problem.

**Comment by praiskup** [comment]
Thanks, I've built the distgen v0.15dev package successfully!  https://copr.fedorainfracloud.org/coprs/praiskup/distgen/builds/
