### ISSUE TITLE
Experiment with streaming jinja feature

### ISSUE THREAD

**Issue by praiskup** [devexp-db/distgen#42]
http://jinja.pocoo.org/docs/2.9/api/#jinja2.Template

**Comment by TomasTomecek** [comment]
the streaming looks neat! I fear it will take quite some time to use it in distgen

**Comment by praiskup** [comment]
I'll take a look asap;  it sounds rather trivial for the non-recursive approach.

**Comment by praiskup** [comment]
My mistake.  Unfortunately, jinja doesn't support input streaming and (according to upstream issue 540) it probably won't in future.  I don't see much benefit in output straming, so my motivation to move this forward burned out...

It would be awesome if we could let `dg` work as general unix utility in pipes, like `some_command | dg --with --opts --template - | some_other_command` without storing the whole template into memory, but this is not something we can implement today..  closing for now.
