### ISSUE TITLE
The `yaml` shoulnd't be needed for `--distro` option

### ISSUE THREAD

**Issue by praiskup** [devexp-db/distgen#58]
E.g. we should use `--distro fedora-26-x86_64` instead of `--distro fedora-26-x86_64.yaml`.  This would be incompatible change, so maybe we could make both versions "equivalent" to each other?

**Comment by bkabrda** [comment]
+1, we just need to limit this to the default config files - for user defined config files, we need to be able to accept arbitrarily named files, e.g. we shouldn't assume that they end with `.yaml`. Does that make sense?
