### ISSUE TITLE
The default --distro should match the fedora/centos version it is running on

### ISSUE THREAD

**Issue by praiskup** [devexp-db/distgen#64]
During build-time, specfile should probably set the default --distro flag to:
```bash
. /etc/os-release
distro="$ID-$VERSION_ID-`uname -i`"
```

So by default /bin/dg could generate templates suited "for the build machine".

**Comment by bkabrda** [comment]
I have to say I'm a bit torn on this. On the one hand it seems to be convenient, OTOH it makes the same distgen execution work differently based on the system it's running on, which I don't like. I think it should always work the same way *regardless* of the system it's run on.

**Comment by praiskup** [comment]
Not hard requirement, really ... Thinking about `dg` as "compiler" or macro language (say rpm), you also have some defaults depending on the system...

I came here because I was just thinking what should be the sane default (and fedora-21 is definitely not good status quo).  So any counter proposal? :-)

**Comment by bkabrda** [comment]
Right, fedora-21 is not a good status quo. My counter proposal would be no default and mandating that the user always has to choose explicitly.

**Comment by praiskup** [comment]
>  On the one hand it seems to be convenient

Yes, I was thinking about using distgen as a "compile"  for some of my tests scripts for fedora CI, e.g. and I would love to avoid detecting the system version over and over again..

> I think it should always work the same way regardless of the system it's run on.

Then setting the default to `fedora-rawhide-x86_64` could help, but the "distconf" will certainly change with new versions of distgen, so it is not 100% bullet proof.  Plus, the `--distro` option is still an option, it won't disappear.

Theoretically could have '/usr/share/distgen/distconf/auto.yaml' pointing to the actual distro config...  This is not easy to do for pipy package .... so for pipy (if the auto.yaml is not present) we could point to fedora rawhide..?

**Comment by praiskup** [comment]
> Right, fedora-21 is not a good status quo. My counter proposal would be no default and mandating that the user always has to choose explicitly.

Agreed, but still -> having `--distro auto` would be convenient thing :-/

**Comment by praiskup** [comment]
Just an idea: What about to have `--distro auto` option, make it a default and detect the system "dynamically"?  I like the minimalism, and the fact that the only mandatory option is `--template` at least for debugging (and theoretically, there might be distro-agnostic templates, too).

**Comment by bkabrda** [comment]
I think that's probably a good compromise for now, so no objections on my side.
