### ISSUE TITLE
Specify key-value pair in matrix section

### ISSUE THREAD

**Issue by mcyprian** [devexp-db/distgen#68]
I am trying to reduce an amount of maintenance work in [s2i-python container](https://github.com/mcyprian/s2i-python-container) using distgen. My impression is that distgen is very nice tool for this purpose.

Small issue I was dealing with is that key-value pairs specified in multispec.yml affect either all Dockerfiles related to one distro or all Dockerfiles for some python version. There is a couple of cases when some value is needed only for one combination of the matrix.  For example python 2.7 centos Dockerfile contains some extra packages to be installed, but python 2.7 rhel Dockerfile doesn't.

My solution for now is using [spec files](https://github.com/mcyprian/s2i-python-container/commit/da37e6a2770c0432a2b40152506059445cebaefc#diff-2d34fc218ad7d05e838430f01a604924R1) to store values for such cases.

My question is whether some mechanism to define this values in matrix section of the multispec could be added. I am willing to prepare PR, but I would like to know your opinion on this first.

**Comment by bkabrda** [comment]
Yeah, this is something that is missing and I'd be glad to accept a PR that would fix this. I can imagine something that would extend usage the `matrix` section [1]. Adding a key like `combination_extras` that would specify the combination very much like `matrix.exclude` and would contain `extras`, which would be a mapping of key-value pairs that would be only added to this combination.

Does that make sense?

[1] http://distgen.readthedocs.io/en/latest/spec_multispec.html#multispecs

**Comment by mcyprian** [comment]
@bkabrda tottaly! I will take a look at the implementation, in case I have some additional questions I will let you know, Thanks.
