### ISSUE TITLE
New release v1?

### ISSUE THREAD

**Issue by praiskup** [devexp-db/distgen#77]
There's quite a few changes merged into master, and few PRs to be merged.
How do you feel about wrapping new distgen version soon?

**Comment by bkabrda** [comment]
+1, let's release all the new features and get some feedback.

**Comment by mcyprian** [comment]
New release will be appreciated, we have to use unreleased distgen from master branch to get adjusted jinja2 behavior [here](https://github.com/sclorg/s2i-python-container/pull/259).

**Comment by torsava** [comment]
The [s2i-python-container](https://github.com/sclorg/s2i-python-container) needs the new changes in master, and it's pretty awkward describing in README how to install distgen without any usable release for us.

A new release would be greatly appreciated!

**Comment by praiskup** [comment]
@bkabrda there's only one issue I'm afraid of -- #69, and I'm curious whether we
could review to proposed fix, or if that would be OK to ship the release without having
that fixed.

**Comment by bkabrda** [comment]
Distgen 1.1 was released and should work both in virtualenvs as well as when pip-installed either systemwide or locally for user. Closing this issue.
